version: '2'
services:
  apache:
    build: .docker/apache
    container_name: discounts_apache
    ports:
    - 80:80
    volumes:
    - .:/home/wwwroot/discounts
    depends_on:
    - php

  mysql:
    image: mysql:5.7
    container_name: db
    volumes:
    - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: --skip-symbolic-links=1

  php:
    build: .docker/php
    container_name: discounts_php
    volumes:
    - .:/home/wwwroot/discounts
    depends_on:
    - mysql